routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/home', function(){ 
	return redirect()->route('task.index'); 
});

Route::get('/', 'TaskController@index');

Route::resource('/task', 'TaskController');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $table = 'tasks';

    protected $fillable = [
    	'name', 'user_id',
    ];

    public function users()
    {
        return $this->hasMany('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'task_id',
        'is_admin',
    ];

    

    public function getId()
    {
        return $this->id;
    }


    public function tasks()
    {
        return $this->belongsTo('App\Task');
    }

    public function isAdmin()
    {
        return $this->is_admin;
    }
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\Task;
use App\User;

use Illuminate\Http\Request;
use Illuminate\Support\ServiceProvider;

class TaskController extends Controller
{   
    public function __construct ()
    {

        $this->middleware('auth', ['except' => ['index']]);

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {   
        if (Auth::check() && !Auth::user()->isAdmin()) {
            $task = Auth::user()->getId();
            $tasks = Task::where('user_id', $task)->get();
        } else {
            $tasks = Task::all();
        }
        return view('task.index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $users = User::all();
        $selectUsers = array();

        foreach ($users as $user) {
            $selectUsers[$user->id] = $user->name;
        }

        return view('task.create', compact('selectUsers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $success = Task::create($request->all());
        return redirect()->route('task.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::find($id);

        $users = User::all();
        $selectUsers = array();

        foreach ($users as $user) {
            $selectUsers[$user->id] = $user->name;
        }

        return view('task.create', compact('task', 'selectUsers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Task::find($id)->update($request->all());

        return redirect()->route('task.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Task::find($id)->delete();

        return redirect()->route('task.index');
    }
}

resources/views/home.blade.php
@extends('main')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                   @if(Auth::guest())
                        You are quest, please login
                    @else
                        You don't have permission
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout/footer.blade.php
	
	</body>
</html>

resources/views/layout/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Tasks list</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}">
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ url('/logout') }}"
                                        onclick="event.preventDefault();
                                               document.getElementById('logout-form').submit();">
                                            Logout
                                    </a>

                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                       {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
       	</div>
    </nav>
	

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('Work List', 'Work List') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/main.blade.php
@include("layout.header")

<main>
	<div class="container">
	
		@yield("content") 
	</div>
</main>

@include("layout.footer")

resources/views/task/create.blade.php
@extends('main')

@section('content')

		@if(isset($task))
		{{ Form::open(['route' => ['task.update', $task->id], "method" => "POST"]) }}
		<input type="hidden" name="_method" value="PUT">
		@else

		{!! Form::open(['url' => '/task', 'method' => "POST"]) !!}
		@endif
		<h3>Create task</h3>

		{{ Form::label('Name') }}<br>
		@if(isset($task))
			{{ Form::text('name', $task->name, ['class' => 'form-control']) }}
		@else
			{{ Form::text('name','',['class' => 'form-control']) }}<br>
		@endif

		{{ Form::label('Users') }}<br>
		@if(isset($task))
			{{ Form::select('user_id', $selectUsers, $task->user_id, ['class' => 'btn btn-default dropdown-toggle']) }}<br>
		@else
			{{ Form::select('user_id', $selectUsers, ['class' => 'btn btn-default dropdown-toggle']) }}
		@endif
	{!! Form::submit('Save', ['class' => 'btn btn-info btn-sm btnSave']); !!}
	{!! Form::close() !!}

	@if(isset($task))

	{{ Form::open(['route' => ['task.destroy', $task->id], "method" => "POST"]) }}
		<input type="hidden" name="_method" value="DELETE">

		{{ csrf_field() }}

	
		{!! Form::submit('Detele', ['class' => 'btn btn-danger btn-sm btnDelete']); !!}
	{!! Form::close() !!}

	@endif

@endsection

resources/views/task/index.blade.php
@extends('main')

@section('content')

	<h1>Task list</h1>
	
	@if(!Auth::guest() && Auth::user()->is_admin) 
    <a href="{{ route('task.create') }}" class="btn btn-info">Add Task</a>
  @else
    
  @endif

  <div class="row">
    <div class="card"> 
      <ul>
        @foreach($tasks as $task)
          <li class="col-md-3 col-sm-6 col-xs-12">
            <div class="card-block">
							<h4>{{ $task->name }}</h4>
              @if(!Auth::guest() && Auth::user()->is_admin)
								<a href="{{ route('task.edit', $task->id) }}" class="btn btn-success btn-xs">Edit</a><br>
              @else

              @endif

              @if(Auth::user() && !Auth::user()->is_admin )
                <form>
                  <label for="option1">Task completed </label>
                  <input type="checkbox" id="option1">
                </form>
              @else

              @endif
            </div>
          </li>
        @endforeach
      </ul>
    </div>
  </div>
@endsection